import { Link } from "react-router-dom"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import { ArrowRight, BookOpen, Calendar } from "lucide-react"
import { publishedEditorialTopics, editorialAudit } from "@/data/ghana-editorial-library"
import { useSeoMeta } from "@/hooks/useSeoMeta"

export default function Blog() {
  useSeoMeta({ title: "Ghana Data, Telecom & Subscription Guides", description: "Verified Ghana-focused guides on mobile data, telecom networks, internet usage, and digital subscriptions.", canonicalPath: "/blog", ogImage: "https://dataplug.store/images/blog-general-data.png" })
  const posts = publishedEditorialTopics
  const schema = { "@context": "https://schema.org", "@type": "Blog", name: "DataPlug Ghana Knowledge Center", url: "https://dataplug.store/blog", description: "Ghana-focused telecom and digital subscription guides.", publisher: { "@type": "Organization", name: "DataPlug Ghana", url: "https://dataplug.store" } }
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><div className="min-h-screen flex flex-col"><Navbar /><main id="main-content" className="flex-1"><header className="border-b border-border py-12 md:py-16"><div className="container max-w-5xl mx-auto px-4 text-center"><div className="inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary mb-4"><BookOpen className="h-3 w-3" aria-hidden="true" />DataPlug Knowledge Center</div><h1 className="font-display text-3xl md:text-5xl font-bold text-balance text-foreground mb-4">Ghana Data, Telecom & Subscription Guides</h1><p className="text-muted-foreground text-base md:text-lg max-w-2xl mx-auto leading-relaxed">Practical, source-conscious answers for people using mobile data, internet services, and digital subscriptions in Ghana.</p><p className="mt-3 text-xs text-muted-foreground">Editorial library: {editorialAudit.totalTopics} distinct topic records. Published guides are reviewed before volatile claims are added.</p></div></header><section className="container max-w-5xl mx-auto px-4 py-12" aria-label="Published Ghana articles"><div className="grid gap-6 md:grid-cols-2">{posts.map((post) => <article key={post.id} className="overflow-hidden rounded-xl border border-border bg-card hover:border-primary/40 transition-colors group"><Link to={post.slug} className="block"><img src={post.coverImage} alt={post.coverAlt} width="1280" height="720" loading="lazy" className="aspect-video w-full object-cover" /><div className="p-6 space-y-3"><div className="flex flex-wrap items-center gap-3"><span className="rounded-full bg-primary/10 px-2.5 py-0.5 text-xs font-semibold text-primary">{post.cluster}</span><span className="flex items-center gap-1 text-xs text-muted-foreground"><Calendar className="h-3 w-3" aria-hidden="true" />{new Date(post.publicationDate || "2026-08-15").toLocaleDateString("en-GH", { year: "numeric", month: "long", day: "numeric" })}</span></div><h2 className="font-display text-lg md:text-xl font-bold text-foreground group-hover:text-primary transition-colors text-balance">{post.title}</h2><p className="text-muted-foreground text-sm leading-relaxed">{post.metaDescription}</p><div className="flex items-center gap-1 text-sm font-medium text-primary">Read guide <ArrowRight className="h-4 w-4" aria-hidden="true" /></div></div></Link></article>)}</div></section></main><Footer /></div></>
}
