import { useEffect, useState } from "react";
import { Save } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useToast } from "@/hooks/use-toast";

const fields = ["admin_price_per_1000", "min_price_per_1000", "max_price_per_1000", "agent_price_per_1000", "subagent_price_per_1000", "sub_subagent_price_per_1000"] as const;
type ProviderService = { service: number; name: string; category: string; rate: string; min: string; max: string };
const fallbackServices: ProviderService[] = [{ service: 1, name: "Followers", category: "TikTok", rate: "0.90", min: "50", max: "10000" }];
const labels: Record<string, string> = { admin_price_per_1000: "User price / 1,000", min_price_per_1000: "Minimum reseller price", max_price_per_1000: "Maximum reseller price", agent_price_per_1000: "Agent price / 1,000", subagent_price_per_1000: "Subagent price / 1,000", sub_subagent_price_per_1000: "Sub-subagent price / 1,000" };
export default function AdminSocialBoostPricing() {
  const { toast } = useToast(); const [values, setValues] = useState<Record<string, number>>({}); const [saving, setSaving] = useState(false); const [services, setServices] = useState<ProviderService[]>(fallbackServices); const [servicePrices, setServicePrices] = useState<Record<number, number>>({});
  useEffect(() => { (supabase as any).from("social_boost_pricing").select(fields.join(",")).eq("id", true).maybeSingle().then(({ data, error }: any) => { if (error) toast({ title: "Could not load Social Boost pricing", description: error.message, variant: "destructive" }); setValues(Object.fromEntries(fields.map((field) => [field, Number(data?.[field] ?? 0)]))); }); supabase.functions.invoke("social-boost", { body: { action: "services" } }).then(({ data }) => { if (Array.isArray(data) && data.length) { setServices(data); setServicePrices(Object.fromEntries(data.map((item: ProviderService) => [item.service, Number(item.rate)]))); } }); }, [toast]);
  const save = async () => { setSaving(true); const { error } = await (supabase as any).from("social_boost_pricing").update({ ...values, updated_at: new Date().toISOString() }).eq("id", true); const serviceRows = services.map((service) => ({ service_id: service.service, service_name: service.name, category: service.category, provider_rate: Number(service.rate) || 0, admin_price_per_1000: servicePrices[service.service] ?? Number(service.rate), min_quantity: Number(service.min) || 1, max_quantity: Number(service.max) || 50000, updated_at: new Date().toISOString() })); const { error: serviceError } = await (supabase as any).from("social_boost_service_pricing").upsert(serviceRows, { onConflict: "service_id" }); setSaving(false); const finalError = error ?? serviceError; toast(finalError ? { title: "Pricing not saved", description: finalError.message, variant: "destructive" } : { title: "Social Boost pricing saved" }); };
  return <div className="rounded-xl border border-cyan-500/30 bg-cyan-500/5 p-4"><h3 className="text-lg font-semibold">Social Boost pricing</h3><p className="mb-4 text-sm text-muted-foreground">Set the global bounds and then set the selling price for every sourced Social Boost service individually.</p><div className="mb-6 overflow-x-auto rounded-xl border border-border"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Service</th><th className="p-3">Provider rate</th><th className="p-3">Min</th><th className="p-3">Max</th><th className="p-3">Admin selling price / 1K</th></tr></thead><tbody>{services.map((service) => <tr key={service.service} className="border-b last:border-0"><td className="p-3 font-medium">{service.category} · {service.name}<span className="block text-xs text-muted-foreground">ID {service.service}</span></td><td className="p-3">{service.rate}</td><td className="p-3">{Number(service.min).toLocaleString()}</td><td className="p-3">{Number(service.max).toLocaleString()}</td><td className="p-3"><Input type="number" min={values.min_price_per_1000 || 0.01} max={values.max_price_per_1000 || undefined} step="0.01" value={servicePrices[service.service] ?? Number(service.rate)} onChange={(event) => setServicePrices((current) => ({ ...current, [service.service]: Number(event.target.value) || 0 }))} /></td></tr>)}</tbody></table></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{fields.map((field) => <label key={field} className="space-y-2 text-sm font-medium">{labels[field]}<Input type="number" min="0.01" step="0.01" value={values[field] ?? 0} onChange={(event) => setValues((current) => ({ ...current, [field]: Number(event.target.value) || 0 }))} /></label>)}</div><Button className="mt-4" onClick={save} disabled={saving}><Save className="mr-2 h-4 w-4" />{saving ? "Saving..." : "Save Social Boost pricing"}</Button></div>;
}
