import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { KeyRound, Save, Plus, Trash2 } from "lucide-react";

type ServiceType = "public_shared" | "private_shared";
type Service = { id: string; name: string; slug: string; category: string; description: string; price: number; active: boolean; logo_url: string | null; official_url: string | null; service_type: ServiceType; is_free: boolean };
type Credential = { id?: string; service_id: string; slot_number: number; email: string | null; password: string | null; instructions: string | null; active: boolean };
const categories = ["Streaming & Entertainment", "Writing & Productivity", "Education & Skills", "Developer Tools & Coding", "Gaming Bots & Mods", "Design & Creative", "Finance & Charting", "Language Learning", "Document Management", "AI & Research"];
const emptySlot = (service_id: string, slot_number: number): Credential => ({ service_id, slot_number, email: "", password: "", instructions: "", active: true });

export default function AdminDigitalServicesManager() {
  const { toast } = useToast();
  const [services, setServices] = useState<Service[]>([]); const [serviceType, setServiceType] = useState<ServiceType>("public_shared"); const [credentials, setCredentials] = useState<Record<string, Credential[]>>({}); const [saving, setSaving] = useState<string | null>(null);
  const [newService, setNewService] = useState({ name: "", slug: "", category: categories[0], description: "", price: "", logo_url: "", is_free: false, service_type: "public_shared" as ServiceType });
  const load = async () => { const [{ data: serviceRows, error: serviceError }, { data: credentialRows }] = await Promise.all([supabase.from("digital_services").select("id,name,slug,category,description,price,active,logo_url,official_url,service_type,is_free").order("service_type").order("category").order("name"), supabase.from("digital_service_credentials").select("id,service_id,slot_number,email,password,instructions,active").order("slot_number")]); if (serviceError) { toast({ title: "Services unavailable", description: serviceError.message, variant: "destructive" }); return; } const rows = (serviceRows as Service[]) || []; setServices(rows); const grouped: Record<string, Credential[]> = {}; ((credentialRows as Credential[]) || []).forEach((row) => { (grouped[row.service_id] ||= []).push(row); }); setCredentials(grouped); };
  useEffect(() => { void load(); }, []);
  const createService = async () => { const payload = { name: newService.name.trim(), slug: newService.slug.trim() || newService.name.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-"), category: newService.category, description: newService.description.trim(), price: newService.is_free ? 0 : Number(newService.price), logo_url: newService.logo_url.trim() || null, is_free: newService.is_free, service_type: newService.service_type, active: true, icon: "sparkles" }; if (!payload.name || !payload.description || (!payload.is_free && (!Number.isFinite(payload.price) || payload.price < 0))) { toast({ title: "Check service details", description: "Enter a name, description, and valid price.", variant: "destructive" }); return; } const { error } = await supabase.from("digital_services").insert(payload); if (error) { console.error("[v0] Service creation failed:", error); toast({ title: "Service not created", description: error.message, variant: "destructive" }); return; } setNewService({ name: "", slug: "", category: categories[0], description: "", price: "", logo_url: "", is_free: false, service_type: newService.service_type }); toast({ title: "Service created" }); await load(); };
  const updateSlot = (serviceId: string, slotNumber: number, patch: Partial<Credential>) => setCredentials((current) => ({ ...current, [serviceId]: (current[serviceId] || []).map((slot) => slot.slot_number === slotNumber ? { ...slot, ...patch } : slot) }));
  const addSlot = (serviceId: string) => setCredentials((current) => { const slots = current[serviceId] || []; const next = Math.max(0, ...slots.map((slot) => slot.slot_number)) + 1; return { ...current, [serviceId]: [...slots, emptySlot(serviceId, next)] }; });
  const removeSlot = (serviceId: string, slotNumber: number) => setCredentials((current) => ({ ...current, [serviceId]: (current[serviceId] || []).filter((slot) => slot.slot_number !== slotNumber) }));
  const save = async (service: Service) => { setSaving(service.id); const serviceUpdate = { price: service.is_free ? 0 : Number(service.price), is_free: service.is_free, logo_url: service.logo_url || null, updated_at: new Date().toISOString() }; const { error: serviceError } = await supabase.from("digital_services").update(serviceUpdate).eq("id", service.id); const slots = credentials[service.id] || []; const { error: credentialError } = await supabase.from("digital_service_credentials").upsert(slots.map(({ id, ...slot }) => ({ ...slot, updated_at: new Date().toISOString() })), { onConflict: "service_id,slot_number" }); setSaving(null); if (serviceError || credentialError) toast({ title: "Save failed", description: serviceError?.message || credentialError?.message, variant: "destructive" }); else { toast({ title: "Service saved" }); await load(); } };
  const visible = services.filter((service) => service.service_type === serviceType);
  return <div className="space-y-6"><div className="flex w-fit gap-2 rounded-xl border border-border bg-muted/30 p-1"><button type="button" onClick={() => setServiceType("public_shared")} className={`rounded-lg px-4 py-2 text-sm font-medium ${serviceType === "public_shared" ? "bg-primary text-primary-foreground" : "text-muted-foreground"}`}>Public Shared Account</button><button type="button" onClick={() => setServiceType("private_shared")} className={`rounded-lg px-4 py-2 text-sm font-medium ${serviceType === "private_shared" ? "bg-primary text-primary-foreground" : "text-muted-foreground"}`}>Private Shared Account</button></div>
    <Card><CardHeader><CardTitle>Add service</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Input placeholder="Service name" value={newService.name} onChange={(e) => setNewService({ ...newService, name: e.target.value })} /><Input placeholder="Slug (optional)" value={newService.slug} onChange={(e) => setNewService({ ...newService, slug: e.target.value })} /><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={newService.category} onChange={(e) => setNewService({ ...newService, category: e.target.value })}>{categories.map((category) => <option key={category}>{category}</option>)}</select><Input type="number" min="0" step="0.01" placeholder="Price (GHC)" disabled={newService.is_free} value={newService.price} onChange={(e) => setNewService({ ...newService, price: e.target.value })} /><Input placeholder="Logo URL (optional)" value={newService.logo_url} onChange={(e) => setNewService({ ...newService, logo_url: e.target.value })} /><Textarea className="md:col-span-2" placeholder="Description" value={newService.description} onChange={(e) => setNewService({ ...newService, description: e.target.value })} /><label className="flex items-center gap-2 text-sm md:col-span-2"><input type="checkbox" checked={newService.is_free} onChange={(e) => setNewService({ ...newService, is_free: e.target.checked })} /> Free service — no payment required</label><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={newService.service_type} onChange={(e) => setNewService({ ...newService, service_type: e.target.value as ServiceType })}><option value="public_shared">Public Shared Account</option><option value="private_shared">Private Shared Account</option></select><Button onClick={() => void createService()}><Plus className="mr-2 h-4 w-4" />Add service</Button></CardContent></Card>
    <div className="space-y-4">{visible.map((service) => <Card key={service.id} className="overflow-hidden"><CardHeader className="flex-row items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 p-2">{service.logo_url ? <img src={service.logo_url} alt="" className="h-full w-full object-contain" /> : <KeyRound className="h-5 w-5 text-primary" />}</div><div><CardTitle>{service.name}</CardTitle><Badge variant="outline">{service.is_free ? "Free" : `GHC ${Number(service.price).toFixed(2)}`}</Badge></div></div><Switch checked={service.active} onCheckedChange={async (active) => { await supabase.from("digital_services").update({ active }).eq("id", service.id); setServices((all) => all.map((item) => item.id === service.id ? { ...item, active } : item)); }} /></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><Input value={service.logo_url || ""} placeholder="Logo URL" onChange={(e) => setServices((all) => all.map((item) => item.id === service.id ? { ...item, logo_url: e.target.value } : item))} /><Input type="number" disabled={service.is_free} value={service.is_free ? "0" : service.price} onChange={(e) => setServices((all) => all.map((item) => item.id === service.id ? { ...item, price: Number(e.target.value) } : item))} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={service.is_free} onChange={(e) => setServices((all) => all.map((item) => item.id === service.id ? { ...item, is_free: e.target.checked } : item))} /> Free service</label></div><div className="space-y-3"><div className="flex items-center justify-between"><Label>Login slots</Label><Button size="sm" variant="outline" onClick={() => addSlot(service.id)}><Plus className="mr-1 h-4 w-4" />Add slot</Button></div>{(credentials[service.id] || []).map((slot) => <div key={slot.slot_number} className="grid gap-2 rounded-xl border border-border p-3 md:grid-cols-[auto_1fr_1fr_1fr_auto]"><Badge variant="secondary">Slot {slot.slot_number}</Badge><Input placeholder="Login email" value={slot.email || ""} onChange={(e) => updateSlot(service.id, slot.slot_number, { email: e.target.value })} /><Input placeholder="Login password" value={slot.password || ""} onChange={(e) => updateSlot(service.id, slot.slot_number, { password: e.target.value })} /><Input placeholder="Instructions" value={slot.instructions || ""} onChange={(e) => updateSlot(service.id, slot.slot_number, { instructions: e.target.value })} /><Button size="icon" variant="ghost" onClick={() => removeSlot(service.id, slot.slot_number)} aria-label="Remove login slot"><Trash2 className="h-4 w-4 text-destructive" /></Button></div>)}</div><Button onClick={() => void save(service)} disabled={saving === service.id}><Save className="mr-2 h-4 w-4" />{saving === service.id ? "Saving…" : "Save service"}</Button></CardContent></Card>)}</div></div>;
}
