import { useEffect, useState } from "react";
import { Save } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useToast } from "@/hooks/use-toast";

type ProviderService = { service: number; name: string; category: string; rate: string; min: string; max: string };
type ServicePrice = { admin: number; default: number; max: number };
const fallback: ProviderService[] = [{ service: 1, name: "Followers", category: "TikTok", rate: "0.90", min: "50", max: "50000" }];

export default function AdminSocialBoostPricing() {
  const { toast } = useToast();
  const [services, setServices] = useState<ProviderService[]>(fallback);
  const [prices, setPrices] = useState<Record<number, ServicePrice>>({});
  const [saving, setSaving] = useState(false);
  useEffect(() => { supabase.functions.invoke("social-boost", { body: { action: "services" } }).then(({ data }) => { if (Array.isArray(data) && data.length) setServices(data); }); }, []);
  useEffect(() => { (supabase as any).from("social_boost_service_pricing").select("service_id,admin_price_per_1000,default_price_per_1000,max_reseller_price_per_1000").then(({ data }: any) => { if (Array.isArray(data)) setPrices(Object.fromEntries(data.map((row: any) => [row.service_id, { admin: Number(row.admin_price_per_1000), default: Number(row.default_price_per_1000), max: Number(row.max_reseller_price_per_1000) }]))); }); }, []);
  const update = (id: number, field: keyof ServicePrice, value: number) => setPrices((current) => ({ ...current, [id]: { admin: current[id]?.admin ?? 0, default: current[id]?.default ?? 0, max: current[id]?.max ?? 0, [field]: value } }));
  const save = async () => { setSaving(true); const rows = services.map((service) => { const p = prices[service.service] ?? { admin: Number(service.rate), default: Number(service.rate), max: Number(service.rate) }; return { service_id: service.service, service_name: service.name, category: service.category, provider_rate: Number(service.rate), admin_price_per_1000: p.admin, default_price_per_1000: p.default, max_reseller_price_per_1000: p.max, min_quantity: Number(service.min), max_quantity: Number(service.max), updated_at: new Date().toISOString() }; }); const { error } = await (supabase as any).from("social_boost_service_pricing").upsert(rows, { onConflict: "service_id" }); setSaving(false); toast(error ? { title: "Pricing not saved", description: error.message, variant: "destructive" } : { title: "Social Boost pricing saved" }); };
  return <section className="rounded-2xl border border-cyan-500/30 bg-cyan-500/5 p-4"><h3 className="text-lg font-semibold">Social Boost service pricing</h3><p className="mb-4 text-sm text-muted-foreground">Set the customer price, the default reseller price, and the maximum price an agent, subagent, or sub-subagent may publish.</p><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b text-left"><th className="p-3">Sourced service</th><th className="p-3">Provider rate</th><th className="p-3">User price / 1K</th><th className="p-3">Default reseller / 1K</th><th className="p-3">Maximum reseller / 1K</th></tr></thead><tbody>{services.map((service) => { const p = prices[service.service] ?? { admin: Number(service.rate), default: Number(service.rate), max: Number(service.rate) }; return <tr key={service.service} className="border-b last:border-0"><td className="p-3 font-medium">{service.category} · {service.name}<span className="block text-xs text-muted-foreground">ID {service.service} · {service.min}–{service.max}</span></td><td className="p-3">{service.rate}</td><td className="p-3"><Input type="number" min="0.01" step="0.01" value={p.admin} onChange={(e) => update(service.service, "admin", Number(e.target.value) || 0)} /></td><td className="p-3"><Input type="number" min="0.01" step="0.01" value={p.default} onChange={(e) => update(service.service, "default", Number(e.target.value) || 0)} /></td><td className="p-3"><Input type="number" min={p.default || 0.01} step="0.01" value={p.max} onChange={(e) => update(service.service, "max", Number(e.target.value) || 0)} /></td></tr>; })}</tbody></table></div><Button className="mt-4" onClick={save} disabled={saving}><Save className="mr-2 h-4 w-4" />{saving ? "Saving..." : "Save Social Boost pricing"}</Button></section>;
}
