import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, ChevronDown, Clock3, Info, Truck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { normalizeOrderStatus } from "@/utils/orderStatus";

type Network = "mtn" | "mtn_express" | "telecel" | "airteltigo";
type Setting = { network: Network; enabled: boolean; source: "manual" | "orders" | "fake"; min_minutes: number; max_minutes: number; rotation_minutes: number; fake_enabled: boolean; fake_prefix: string; fake_count: number; status_color?: "green" | "red" | "yellow"; message: string };
type Order = { id?: string | number; customer_number?: string | null; network: string; status: string; fulfillment_status: string; order_status: string; created_at?: string | null; updated_at?: string | null };
const labels: Record<Network, string> = { mtn: "MTN", mtn_express: "MTN Express", telecel: "Telecel", airteltigo: "AirtelTigo" };
const defaults: Setting[] = ["mtn", "mtn_express", "telecel", "airteltigo"].map((network) => ({ network: network as Network, enabled: true, source: network === "mtn_express" ? "fake" : "manual", min_minutes: 30, max_minutes: 240, rotation_minutes: 30, fake_enabled: network === "mtn_express", fake_prefix: network === "telecel" ? "020" : network === "airteltigo" ? "026" : "024", fake_count: 10, message: `${labels[network as Network]} orders are being processed. Please allow the estimated delivery window.` }));
const normalize = (value?: string | null): Network | null => { const n = (value ?? "").toLowerCase().trim().replace(/[\s-]+/g, "_"); if (["mtn_express", "mtnexpress", "express_mtn"].includes(n)) return "mtn_express"; if (["mtn", "mtn_4g", "mtn_data"].includes(n)) return "mtn"; if (["telecel", "vodafone"].includes(n)) return "telecel"; if (["airteltigo", "airtel_tigo", "airtel", "tigo"].includes(n)) return "airteltigo"; return null; };
const date = (v?: string | null) => v ? new Intl.DateTimeFormat("en-GH", { month: "short", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(v)) : "—";
const duration = (a?: string | null, b?: string | null) => { if (!a || !b) return "—"; const m = Math.max(0, Math.round((new Date(b).getTime() - new Date(a).getTime()) / 60000)); if (m === 0) return "instant"; return m < 60 ? `${m} minutes` : `${Math.floor(m / 60)}h ${m % 60 ? `${m % 60}m` : ""}`.trim(); };
const windowText = (m: number) => m < 60 ? `${m} minutes` : `${Math.floor(m / 60)}${m % 60 ? `h ${m % 60}m` : " hours"}`;
const masked = (number?: string | number | null) => { const s = String(number ?? "").replace(/\D/g, ""); return s.length >= 6 ? `${s.slice(0, 3)}****${s.slice(-3)}` : "—"; };
const fakeId = (prefix: string, index: number) => `${(prefix || "024").padEnd(3, "0").slice(0, 3)}${String(1000000 + index * 7919).slice(0, 5)}${String(index).padStart(2, "0")}`;

export default function DeliveryProgressCard() {
  const [network, setNetwork] = useState<Network>("mtn_express"); const [settings, setSettings] = useState<Setting[]>(defaults); const [globalEnabled, setGlobalEnabled] = useState(true); const [orders, setOrders] = useState<Order[]>([]); const [open, setOpen] = useState(false);
  const load = async () => { const [settingsResult, ordersResult] = await Promise.all([supabase.from("delivery_progress_settings").select("network, enabled, source, min_minutes, max_minutes, rotation_minutes, fake_enabled, fake_prefix, fake_count, status_color, message"), supabase.from("orders").select("id, customer_number, network, status, fulfillment_status, order_status, created_at, updated_at").order("updated_at", { ascending: false }).limit(1000)]); const saved = (settingsResult.data as Setting[]) ?? []; setGlobalEnabled((saved.find((s: any) => s.network === "__global__") as any)?.enabled ?? true); setSettings(defaults.map((d) => ({ ...d, ...(saved.find((s) => s.network === d.network) ?? {}) }))); setOrders((ordersResult.data ?? []) as Order[]); };
  useEffect(() => { load(); const channel = supabase.channel("delivery-progress-live").on("postgres_changes", { event: "*", schema: "public", table: "orders" }, load).on("postgres_changes", { event: "*", schema: "public", table: "delivery_progress_settings" }, load).subscribe(); return () => { supabase.removeChannel(channel); }; }, []);
  const item = settings.find((s) => s.network === network);
  const deliveredOrders = useMemo(() => orders.filter((o) => normalize(o.network) === network && normalizeOrderStatus(o) === "delivered" && o.created_at && o.updated_at && new Date(o.updated_at).getTime() >= new Date(o.created_at).getTime()).sort((a, b) => new Date(b.updated_at || 0).getTime() - new Date(a.updated_at || 0).getTime()), [orders, network]);
  const real = deliveredOrders[0];
  const active = orders.filter((o) => normalize(o.network) === network && !["delivered", "refunded", "failed"].includes(normalizeOrderStatus(o))).length;
  const realDurations = deliveredOrders.map((o) => Math.max(0, Math.round((new Date(o.updated_at!).getTime() - new Date(o.created_at!).getTime()) / 60000)));
  const realMin = realDurations.length ? Math.min(...realDurations) : 0;
  const realMax = realDurations.length ? Math.max(...realDurations) : 0;
  const fake = item?.source === "fake" ? { id: fakeId(item.fake_prefix, Math.floor(Date.now() / Math.max(1, item.rotation_minutes * 60000)) % Math.max(1, item.fake_count)), customer_number: `${item.fake_prefix || "024"}${String(1000000 + Math.floor(Date.now() / 60000) % 8999999).slice(0, 7)}`, network, status: "delivered", fulfillment_status: "delivered", order_status: "delivered", created_at: new Date(Date.now() - Math.max(0, item.min_minutes) * 60000).toISOString(), updated_at: new Date().toISOString() } : null;
  if (!globalEnabled || !item || !item.enabled) return null;
  const shown = fake ?? real; const extra = item.source === "orders" ? Math.min(240, Math.floor(active / 100) * 15) : 0;
  const estimateMin = item.source === "orders" && realDurations.length ? realMin : item.min_minutes + extra;
  const estimateMax = item.source === "orders" && realDurations.length ? realMax : item.max_minutes + extra;
  return <Card className="mx-auto mb-8 w-full max-w-5xl overflow-hidden border-violet-400/40 bg-violet-950 text-violet-50 shadow-lg"><CardHeader className="px-5 pb-3 pt-4 sm:px-6"><div className="flex items-center justify-between gap-3"><CardTitle className="flex items-center gap-2 text-lg sm:text-xl"><Truck className="size-5 text-primary" />Delivery Progress</CardTitle><Select value={network} onValueChange={(v) => setNetwork(v as Network)}><SelectTrigger className="h-9 w-36 sm:w-44"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(labels).map(([k, v]) => <SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></div></CardHeader><CardContent className="flex flex-col gap-3 px-5 pb-5 sm:px-6"><div className="flex gap-3 rounded-lg border border-emerald-500/30 bg-emerald-500/5 p-3"><span className={`mt-1 size-3 shrink-0 rounded-full ${item.status_color === "red" ? "bg-red-500" : item.status_color === "yellow" ? "bg-yellow-400" : "bg-emerald-500"}`} /><div><p className="text-sm font-medium leading-5">{item.message}</p><p className="mt-1 text-xs text-muted-foreground">Estimated delivery: <strong className="text-foreground">{windowText(estimateMin)} – {windowText(estimateMax)}</strong></p></div></div><div className="flex gap-3 rounded-lg border border-border bg-background/70 p-3"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-emerald-600" /><div className="min-w-0 text-sm"><p><strong className="text-emerald-700">Last delivered:</strong> <span className="font-medium">{masked(shown?.customer_number)}</span></p><p className="text-muted-foreground">Placed {date(shown?.created_at)} · Delivered {date(shown?.updated_at)} · Took <strong className="text-foreground">{duration(shown?.created_at, shown?.updated_at)}</strong></p></div><Badge variant="outline" className="ml-auto hidden h-fit shrink-0 gap-1 sm:flex"><Clock3 className="size-3" />{labels[network]}</Badge></div><Button variant="ghost" size="sm" className="w-fit gap-2 px-0 text-xs text-muted-foreground" onClick={() => setOpen(!open)}><Info className="size-4" />What should you know?<ChevronDown className={`size-4 ${open ? "rotate-180" : ""}`} /></Button>{open && <p className="text-xs leading-5 text-muted-foreground">This is an estimated delivery window, not a guarantee. Track your own order from the Track Order bar for its actual status.</p>}</CardContent></Card>;
}
