import { useEffect, useState } from "react";
import { Save, Truck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";

type Setting = { network: string; enabled: boolean; source: "manual" | "orders" | "fake"; min_minutes: number; max_minutes: number; rotation_minutes: number; fake_enabled: boolean; fake_prefix: string; fake_count: number; message: string };
const networks = ["mtn", "mtn_express", "telecel", "airteltigo"];
const defaults: Setting[] = networks.map((network) => ({ network, enabled: true, source: network === "mtn_express" ? "fake" : "manual", min_minutes: network === "mtn_express" ? 15 : 30, max_minutes: network === "mtn_express" ? 90 : 240, rotation_minutes: 30, fake_enabled: network === "mtn_express", fake_prefix: network === "telecel" ? "020" : network === "airteltigo" ? "026" : "024", fake_count: 10, message: `${network === "mtn_express" ? "MTN Express" : network.toUpperCase()} orders are being processed. Please allow the estimated delivery window.` }));
const labels: Record<string, string> = { mtn: "MTN", mtn_express: "MTN Express", telecel: "Telecel", airteltigo: "AirtelTigo" };

export default function DeliveryProgressAdmin() {
  const { toast } = useToast();
  const [settings, setSettings] = useState<Setting[]>([]);
  const [saving, setSaving] = useState(false);
  useEffect(() => { supabase.from("delivery_progress_settings").select("network, enabled, source, min_minutes, max_minutes, rotation_minutes, fake_enabled, fake_prefix, fake_count, message").order("network").then(({ data }) => { const saved = (data as Setting[]) ?? []; setSettings(networks.map((network) => ({ ...defaults.find((item) => item.network === network)!, ...(saved.find((item) => item.network === network) ?? {}) }))); }); }, []);
  const update = (network: string, patch: Partial<Setting>) => setSettings((items) => items.map((item) => item.network === network ? { ...item, ...patch } : item));
  const save = async () => { setSaving(true); const { error } = await supabase.rpc("save_delivery_progress_settings", { payload: settings.map(({ network, ...values }) => ({ network, ...values, updated_at: new Date().toISOString() })) }); setSaving(false); toast(error ? { title: "Could not save delivery settings", description: "Run the latest delivery settings SQL, then sign in again as an admin.", variant: "destructive" } : { title: "Delivery settings saved" }); };
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Truck className="size-5 text-primary" />Delivery Progress Controls</CardTitle><p className="text-sm text-muted-foreground">Configure each network independently, including fake progress rotation.</p></CardHeader><CardContent className="flex flex-col gap-4">{settings.map((item) => <div key={item.network} className="flex flex-col gap-4 rounded-lg border border-border p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">{labels[item.network]}</h3><div className="flex items-center gap-2 text-sm"><Switch checked={item.enabled} onCheckedChange={(enabled) => update(item.network, { enabled })} /><Label>Visible</Label></div></div><div className="grid gap-4 sm:grid-cols-3"><div className="flex flex-col gap-2"><Label>Progress source</Label><Select value={item.source} onValueChange={(source: Setting["source"]) => update(item.network, { source, fake_enabled: source === "fake" })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="manual">Manual window</SelectItem><SelectItem value="orders">Read real orders</SelectItem><SelectItem value="fake">Fake delivery progress</SelectItem></SelectContent></Select></div><div className="flex flex-col gap-2"><Label>Minimum minutes</Label><Input type="number" min="2" value={item.min_minutes} onChange={(e) => update(item.network, { min_minutes: Math.max(2, Number(e.target.value)) })} /></div><div className="flex flex-col gap-2"><Label>Maximum minutes</Label><Input type="number" min={item.min_minutes} value={item.max_minutes} onChange={(e) => update(item.network, { max_minutes: Math.max(item.min_minutes, Number(e.target.value)) })} /></div></div><div className="grid gap-4 sm:grid-cols-3"><div className="flex flex-col gap-2"><Label>Change to next order after (minutes)</Label><Input type="number" min="1" value={item.rotation_minutes} onChange={(e) => update(item.network, { rotation_minutes: Math.max(1, Number(e.target.value)) })} /></div><div className="flex flex-col gap-2"><Label>Fake prefix</Label><Input value={item.fake_prefix} maxLength={3} onChange={(e) => update(item.network, { fake_prefix: e.target.value.replace(/\D/g, "").slice(0, 3) })} /></div><div className="flex flex-col gap-2"><Label>Fake orders to rotate</Label><Input type="number" min="1" max="100" value={item.fake_count} onChange={(e) => update(item.network, { fake_count: Math.min(100, Math.max(1, Number(e.target.value))) })} /></div></div><div className="flex flex-col gap-2"><Label>Customer-facing message</Label><Textarea value={item.message} onChange={(e) => update(item.network, { message: e.target.value })} rows={2} /></div></div>)}<Button onClick={save} disabled={saving || !settings.length}><Save data-icon="inline-start" />{saving ? "Saving..." : "Save delivery settings"}</Button></CardContent></Card>;
}
