import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { ChevronDown, ChevronUp, Sparkles, Play, Music, PenLine, Palette, ChartNoAxesCombined, Languages, Brain, Code2, GraduationCap, FileText, Gamepad2, Search, ArrowUpRight, Lock, ShoppingBag } from "lucide-react";

export interface Service { id: string; slug: string; name: string; category: string; description: string; price: number; duration: string | null; icon: string; logo_url: string | null; official_url: string | null; service_type: "public_shared" | "private_shared"; is_free: boolean; active: boolean; help_video_url: string | null; }
const categories = [{ name: "Streaming & Entertainment", icon: Play }, { name: "AI & Research", icon: Brain }, { name: "Design & Creative", icon: Palette }, { name: "Language Learning", icon: Languages }, { name: "Writing & Productivity", icon: PenLine }, { name: "Education & Skills", icon: GraduationCap }, { name: "Document Management", icon: FileText }, { name: "Developer Tools & Coding", icon: Code2 }, { name: "Gaming Bots & Mods", icon: Gamepad2 }, { name: "Finance & Charting", icon: ChartNoAxesCombined }];
const iconMap: Record<string, any> = { play: Play, music: Music, pen: PenLine, palette: Palette, chart: ChartNoAxesCombined, languages: Languages, brain: Brain, code: Code2, graduation: GraduationCap, file: FileText, gamepad: Gamepad2, search: Search };
const fallbackImages: Record<string, string> = { Netflix: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=900&q=80", "Apple Music": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=900&q=80", Spotify: "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?auto=format&fit=crop&w=900&q=80", "iCloud Storage": "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=900&q=80", "Prime Video": "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=900&q=80" };

export default function DigitalServicesCatalog({ onBuy, agentStoreId }: { onBuy: (service: Service) => void; agentStoreId?: string }) {
  const { toast } = useToast();
  const [services, setServices] = useState<Service[]>([]);
  const [serviceType, setServiceType] = useState<"public_shared" | "private_shared">("public_shared");
  const [open, setOpen] = useState<string | null>(null);
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true);
  useEffect(() => { (async () => { setLoading(true); const { data, error } = await supabase.from("digital_services").select("id,slug,name,category,description,price,duration,icon,logo_url,official_url,service_type,is_free,active,help_video_url").eq("service_type", serviceType).order("active", { ascending: false }).order("name"); if (error) toast({ title: "Services unavailable", description: "Please try again shortly.", variant: "destructive" }); let rows = ((data as Service[]) || []).sort((a, b) => Number(b.active) - Number(a.active) || a.name.localeCompare(b.name)); if (agentStoreId && rows.length) { const { data: prices } = await supabase.from("agent_service_pricing").select("service_id,sell_price").eq("agent_store_id", agentStoreId); const byId = new Map((prices || []).map((p: { service_id: string; sell_price: number }) => [p.service_id, Number(p.sell_price)])); rows = rows.map((service) => byId.has(service.id) ? { ...service, price: byId.get(service.id)! } : service); } setServices(rows); setOpen(rows[0]?.category || null); setLoading(false); })(); }, [toast, serviceType, agentStoreId]);
  const filtered = useMemo(() => services.filter((service) => `${service.name} ${service.description} ${service.category}`.toLowerCase().includes(query.toLowerCase())), [services, query]);
  const grouped = useMemo(() => Object.fromEntries(categories.map((category) => [category.name, filtered.filter((service) => service.category === category.name)])), [filtered]);
  return <div className="mx-auto max-w-6xl bg-[#f7f8fc] px-3 pb-16 text-[#111936] sm:px-6">
    <section className="relative overflow-hidden rounded-[28px] bg-[#111936] text-white shadow-2xl"><div className="grid min-h-[290px] items-center md:grid-cols-[1fr_0.9fr]"><div className="relative z-10 p-7 sm:p-10"><p className="mb-4 text-[10px] font-bold uppercase tracking-[0.32em] text-[#8c7cff]">Curated digital services</p><h1 className="max-w-md text-4xl font-black leading-[0.95] tracking-[-0.04em] sm:text-5xl">Premium <span className="text-[#a997ff]">subscriptions</span>, without the friction.</h1><p className="mt-5 max-w-sm text-xs leading-5 text-[#c9cce0]">Choose a service, pay securely, and receive activation help in one private support path.</p><div className="mt-6 flex flex-wrap gap-2"><Button onClick={() => document.getElementById("service-grid")?.scrollIntoView({ behavior: "smooth" })} className="rounded-lg bg-[#7161f4] text-white hover:bg-[#887aff]">Explore services <ArrowUpRight className="ml-1 h-4 w-4" /></Button><span className="rounded-lg border border-white/20 px-3 py-2 text-xs text-[#d8d9e8]">Protected checkout</span><span className="rounded-lg border border-white/20 px-3 py-2 text-xs text-[#d8d9e8]">Private support</span></div></div><div className="hidden h-full min-h-[290px] bg-[radial-gradient(circle_at_40%_30%,#6f63cf,transparent_35%),linear-gradient(135deg,#202951,#090e22)] md:block"><div className="flex h-full items-center justify-center text-8xl opacity-60"><ShoppingBag className="h-24 w-24 text-[#a997ff]" /></div></div></div></section>
    <div className="mt-8 flex items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.28em] text-[#7565ee]">Curated marketplace</p><h2 className="mt-1 text-3xl font-black tracking-[-0.04em]">Find your next service</h2><p className="mt-1 text-xs text-[#69708a]">Clean pricing, real activation, and help when you need it.</p></div><span className="hidden text-[10px] text-[#69708a] sm:block">{filtered.length} services</span></div>
    <div className="mt-5 rounded-xl border border-[#dfe2ee] bg-white p-4 text-xs leading-5 text-[#69708a]"><p className="font-bold text-[#111936]">Choose the right access type</p><p className="mt-1"><strong>Public share</strong> gives you access through a shared service account. <strong>Private share</strong> is an individual access setup. Pay securely, then follow the activation instructions sent after checkout.</p></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><div className="flex flex-1 items-center rounded-xl border border-[#dfe2ee] bg-white px-3 shadow-sm"><Search className="h-4 w-4 text-[#98a0b8]" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search services..." className="w-full bg-transparent px-2 py-3 text-sm outline-none" /></div><div className="flex rounded-xl border border-[#dfe2ee] bg-white p-1"><button onClick={() => setServiceType("public_shared")} className={`rounded-lg px-3 py-2 text-xs font-bold ${serviceType === "public_shared" ? "bg-[#7161f4] text-white" : "text-[#69708a]"}`}>Public share</button><button onClick={() => setServiceType("private_shared")} className={`rounded-lg px-3 py-2 text-xs font-bold ${serviceType === "private_shared" ? "bg-[#7161f4] text-white" : "text-[#69708a]"}`}>Private share</button></div></div>
    <div id="service-grid" className="mt-5 space-y-3">{loading ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[1,2,3].map((n) => <div key={n} className="h-64 animate-pulse rounded-2xl bg-white" />)}</div> : categories.filter(({ name }) => (grouped[name] || []).length).map(({ name, icon: CategoryIcon }) => { const items = grouped[name] || []; const isOpen = open === name; return <section key={name} className="overflow-hidden rounded-2xl border border-[#e1e4ef] bg-white"><button onClick={() => setOpen(isOpen ? null : name)} className="flex w-full items-center justify-between p-4 text-left"><span className="flex items-center gap-3"><span className="rounded-xl bg-[#eeecff] p-2 text-[#7161f4]"><CategoryIcon className="h-4 w-4" /></span><span className="font-bold">{name}<span className="ml-2 text-xs font-normal text-[#8d94aa]">{items.length} services</span></span></span>{isOpen ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}</button>{isOpen && <div className="grid gap-4 border-t border-[#eef0f6] p-3 sm:grid-cols-2 lg:grid-cols-3">{items.map((service) => { const Icon = iconMap[service.icon] || Sparkles; const image = service.logo_url || fallbackImages[service.name] || "https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=900&q=80"; return <article key={service.id} className="group overflow-hidden rounded-2xl border border-[#e0e3ee] bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="relative h-32 overflow-hidden bg-[#161c3d]"><img src={image} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><span className="absolute bottom-2 left-2 rounded-md bg-[#111936]/85 px-2 py-1 text-[10px] font-bold text-white"><Icon className="mr-1 inline h-3 w-3" />{service.name}</span>{service.service_type === "private_shared" && <span className="absolute right-2 top-2 rounded-full bg-white/90 px-2 py-1 text-[10px] font-bold text-[#7161f4]"><Lock className="mr-1 inline h-3 w-3" />Private</span>}</div><div className="p-4"><h3 className="font-bold text-[#202644]">{service.name}</h3><p className="mt-1 min-h-10 text-xs leading-5 text-[#69708a]">{service.description || "Premium access with secure activation support."}</p><div className="mt-4 flex items-end justify-between border-t border-[#eef0f6] pt-3"><div><p className="text-[9px] uppercase text-[#9aa1b5]">Starting from</p><p className="font-black text-[#202644]">GHC {Number(service.price).toFixed(2)}</p></div><Button onClick={() => onBuy(service)} disabled={!service.active} size="sm" className="rounded-lg bg-[#7161f4] text-white hover:bg-[#5d50df]">{service.active ? "Buy now" : "Unavailable"}</Button></div></div></article>; })}</div>}</section>; })}</div>
  </div>;
}
