import { useState } from "react";
import { Eye, EyeOff, ExternalLink } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import type { Service } from "./DigitalServicesCatalog";

const FEE = 1.98;
const youtubeEmbedUrl = (value?: string | null) => { if (!value) return null; try { const url = new URL(value); if (url.hostname.includes("youtu.be")) return `https://www.youtube.com/embed/${url.pathname.slice(1)}`; const id = url.searchParams.get("v"); return id ? `https://www.youtube.com/embed/${id}` : null; } catch { return null; } };

export default function ServicePurchaseDialog({ service, onOpenChange }: { service: Service | null; onOpenChange: (open: boolean) => void }) {
  const { toast } = useToast(); const [phone, setPhone] = useState(""); const [pin, setPin] = useState(""); const [loading, setLoading] = useState(false); const [activationLoading, setActivationLoading] = useState(false); const [showPin, setShowPin] = useState(true); const [credential, setCredential] = useState<{ email: string | null; password: string | null; instructions: string | null } | null>(null);
  const price = Number(service?.price || 0); const total = Math.round(price * (1 + FEE / 100) * 100) / 100; const helpUrl = youtubeEmbedUrl(service?.help_video_url);
  const readError = async (error: unknown, data: any) => { if (data?.error) return data.error; const context = (error as any)?.context; if (context?.clone) { const body = await context.clone().json().catch(() => null); if (body?.error || body?.message) return body.error || body.message; } return (error as any)?.message || "The service request failed. Please try again."; };
  const activate = async () => { if (!service || !/^\d{10}$/.test(phone) || !/^\d{4}$/.test(pin)) { toast({ title: "Check your details", description: "Enter a 10-digit phone number and 4-digit access code.", variant: "destructive" }); return; } setActivationLoading(true); const result = await supabase.functions.invoke("activate-service", { body: { service_id: service.id, phone, pin, free_service: service.is_free === true } }); setActivationLoading(false); if (result.error || !result.data?.credential) { const detail = await readError(result.error, result.data); console.error("[v0] Service activation failed", result.error || result.data); toast({ title: "Access unavailable", description: detail, variant: "destructive" }); return; } setCredential(result.data.credential); };
  const submit = async () => { if (!service) return; if (service.is_free === true) { await activate(); return; } if (!/^\d{10}$/.test(phone) || !/^\d{4}$/.test(pin)) { toast({ title: "Check your details", description: "Enter a 10-digit phone number and 4-digit access code.", variant: "destructive" }); return; } if (!Number.isFinite(price) || price <= 0) { toast({ title: "Payment unavailable", description: "This service is configured as paid but has no valid price.", variant: "destructive" }); return; } setLoading(true); const { data: auth } = await supabase.auth.getUser(); const result = await supabase.functions.invoke("initialize-payment", { body: { amount: total, email: `${phone}@dataplug.store`, phone, service_id: service.id, service_name: service.name, service_type: service.service_type, access_pin: pin, customer_phone: phone, callback_url: `${window.location.origin}/packages?service_payment=verifying`, metadata: { type: "service_payment", service_id: service.id, service_name: service.name, service_type: service.service_type, customer_phone: phone, access_pin: pin, customer_id: auth.user?.id || null, service_payment: true } } }); setLoading(false); if (result.error || !result.data?.authorization_url) { toast({ title: "Payment unavailable", description: await readError(result.error, result.data), variant: "destructive" }); return; } sessionStorage.setItem("pending_service_payment", result.data.reference); window.location.assign(result.data.authorization_url); };
  return <Dialog open={!!service} onOpenChange={onOpenChange}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>{credential ? `${service?.name} access` : service?.name}</DialogTitle><DialogDescription>{credential ? "Your access is ready. Follow the instructions below." : service?.is_free ? "This service is free. Enter your details to activate access." : "Pay first. After verified payment, your assigned login will be available."}</DialogDescription></DialogHeader>{credential ? <div className="space-y-4"><div className="rounded-lg border bg-muted p-4"><p className="text-sm text-muted-foreground">Email / username</p><p className="font-medium">{credential.email || "Not provided"}</p><p className="mt-3 text-sm text-muted-foreground">Password</p><p className="font-medium">{credential.password || "Not provided"}</p>{credential.instructions && <p className="mt-3 text-sm text-muted-foreground">{credential.instructions}</p>}</div>{helpUrl && <div className="space-y-2"><p className="text-sm font-semibold">How to use this service</p><div className="aspect-video overflow-hidden rounded-lg bg-muted"><iframe title={`${service?.name} help video`} src={helpUrl} className="h-full w-full" allowFullScreen /></div></div>}<Button className="w-full" onClick={() => onOpenChange(false)}><ExternalLink className="mr-2 h-4 w-4" />Continue</Button></div> : <div className="space-y-4">{!service?.is_free && <div className="rounded-lg bg-muted p-3 text-sm"><div className="flex justify-between"><span>Service price</span><span>GHC {price.toFixed(2)}</span></div><div className="flex justify-between"><span>Paystack charge</span><span>GHC {(total - price).toFixed(2)}</span></div><div className="mt-2 flex justify-between border-t pt-2 font-bold"><span>Total</span><span>GHC {total.toFixed(2)}</span></div></div>}<div className="space-y-2"><Label htmlFor="service-phone">Phone number</Label><Input id="service-phone" inputMode="numeric" maxLength={10} value={phone} onChange={(event) => setPhone(event.target.value.replace(/\D/g, ""))} /></div><div className="space-y-2"><Label htmlFor="service-pin">Create 4-digit access code</Label><div className="relative"><Input id="service-pin" className="pr-11" inputMode="numeric" maxLength={4} type={showPin ? "text" : "password"} value={pin} onChange={(event) => setPin(event.target.value.replace(/\D/g, ""))} /><button type="button" aria-label={showPin ? "Hide access code" : "Show access code"} className="absolute inset-y-0 right-0 flex w-11 items-center justify-center text-muted-foreground" onClick={() => setShowPin((value) => !value)}>{showPin ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div></div><Button className="w-full" onClick={() => void submit()} disabled={loading || activationLoading}>{loading || activationLoading ? "Working..." : service?.is_free ? "Get free access" : "Continue to payment"}</Button></div>}</DialogContent></Dialog>;
}
