import { useMemo, useRef, useState } from "react";
import { createWorker } from "tesseract.js";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { Check, ChevronDown, Loader2, Send, Upload } from "lucide-react";

type SmsComposerProps = { ownerType: "customer" | "agent"; ownerId?: string };
type Sender = { id: string; sender_id: string; status: "pending" | "approved" | "rejected" };
const readySenders = ["DATAFORALL", "CHEAPDATA", "GETDATA", "DATASTORE"];
const parseNumbers = (value: string) => Array.from(new Set(value.split(/[\n,;\s]+/).map((item) => item.replace(/[^\d+]/g, "")).filter((item) => /^\+?[0-9]{8,15}$/.test(item))));

export default function SmsComposer({ ownerType, ownerId }: SmsComposerProps) {
  const { toast } = useToast();
  const fileRef = useRef<HTMLInputElement>(null);
  const [recipients, setRecipients] = useState(""); const [senderId, setSenderId] = useState(""); const [message, setMessage] = useState(""); const [senders, setSenders] = useState<Sender[]>([]); const [senderOpen, setSenderOpen] = useState(false); const [custom, setCustom] = useState(""); const [ocrLoading, setOcrLoading] = useState(false); const [loading, setLoading] = useState(false);
  const numbers = useMemo(() => parseNumbers(recipients), [recipients]);
  const loadSenders = async () => { const { data } = await supabase.from("sms_sender_ids").select("id,sender_id,status").order("created_at", { ascending: false }); setSenders((data || []) as Sender[]); };
  const submitSender = async () => { const value = custom.trim().toUpperCase(); if (!/^[A-Z0-9 ]{3,11}$/.test(value)) { toast({ title: "Invalid sender ID", description: "Use 3–11 letters, numbers, or spaces.", variant: "destructive" }); return; } const { data: auth } = await supabase.auth.getUser(); if (!auth.user) { toast({ title: "Sign in required", description: "Please sign in before submitting a sender ID.", variant: "destructive" }); return; } const { error } = await supabase.from("sms_sender_ids").insert({ user_id: auth.user.id, sender_id: value }); if (error) { toast({ title: "Could not submit sender ID", description: error.message, variant: "destructive" }); return; } setCustom(""); await loadSenders(); toast({ title: "Submitted for approval", description: `${value} is now pending review.` }); };
  const extractScreenshot = async (file: File) => { setOcrLoading(true); try { const worker = await createWorker("eng"); const result = await worker.recognize(file); await worker.terminate(); const extracted = parseNumbers(result.data.text); if (!extracted.length) toast({ title: "No phone numbers found", description: "Try a clearer screenshot with the numbers visible." }); else { setRecipients((current) => parseNumbers(`${current}\n${extracted.join("\n")}`).join("\n")); toast({ title: "Contacts extracted", description: `${extracted.length} unique number(s) added.` }); } } catch { toast({ title: "Screenshot extraction failed", description: "Please try another image.", variant: "destructive" }); } finally { setOcrLoading(false); } };
  const send = async () => { if (!senderId || !message.trim() || !numbers.length) { toast({ title: "Complete the SMS form", description: "Choose an approved sender, add recipients, and write a message.", variant: "destructive" }); return; } setLoading(true); const { data, error } = await supabase.functions.invoke("txtconnect-sms", { body: { action: "send", owner_type: ownerType, owner_id: ownerId, recipients: numbers, sender_id: senderId, message: message.trim() } }); setLoading(false); if (error || data?.error) { toast({ title: "SMS was not sent", description: data?.error || error?.message || "Please try again.", variant: "destructive" }); return; } toast({ title: "SMS sent", description: `${data.sent || numbers.length} recipient(s) processed.` }); setRecipients(""); setMessage(""); };
  const approved = [...readySenders.map((value) => ({ id: value, sender_id: value, status: "approved" as const })), ...senders.filter((item) => item.status === "approved")];
  return <Card className="border-primary/20"><CardHeader><CardTitle className="flex items-center gap-2"><Send className="h-5 w-5 text-primary" />Send SMS</CardTitle><p className="text-sm text-muted-foreground">Send to one or many contacts. SMS charges are deducted per recipient.</p></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label>Sender ID</Label><div className="relative"><Button type="button" variant="outline" className="w-full justify-between" onClick={() => { setSenderOpen(!senderOpen); if (!senderOpen) void loadSenders(); }}>{senderId || "Choose an approved sender ID"}<ChevronDown className="h-4 w-4" /></Button>{senderOpen && <div className="absolute z-20 mt-1 w-[calc(100%-2rem)] rounded-lg border bg-background p-2 shadow-lg">{approved.map((sender) => <button type="button" key={sender.id} className="flex w-full items-center justify-between rounded-md px-3 py-2 text-left text-sm hover:bg-muted" onClick={() => { setSenderId(sender.sender_id); setSenderOpen(false); }}>{sender.sender_id}<Check className="h-4 w-4 text-primary" /></button>)}<div className="mt-2 border-t pt-2"><Input value={custom} onChange={(event) => setCustom(event.target.value)} placeholder="Custom sender ID" maxLength={11} /><Button type="button" size="sm" className="mt-2 w-full" onClick={() => void submitSender()}>Submit custom ID for approval</Button></div></div>}</div></div><div className="space-y-2"><Label>Recipients ({numbers.length})</Label><div className="flex gap-2"><Textarea value={recipients} onChange={(event) => setRecipients(event.target.value)} placeholder="Paste numbers, one per line or comma-separated" rows={4} /><Button type="button" variant="outline" className="h-10 shrink-0" onClick={() => fileRef.current?.click()} disabled={ocrLoading}>{ocrLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />}<span className="sr-only">Extract contacts from screenshot</span></Button><input ref={fileRef} type="file" accept="image/*" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) void extractScreenshot(file); event.currentTarget.value = ""; }} /></div><p className="text-xs text-muted-foreground">Upload a WhatsApp group screenshot to extract numbers. You can repeat this as often as needed.</p></div><div className="space-y-2"><Label htmlFor={`${ownerType}-sms-message`}>Message</Label><Textarea id={`${ownerType}-sms-message`} value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Write your message..." maxLength={1000} rows={5} /><p className="text-right text-xs text-muted-foreground">{message.length}/1000</p></div><Button onClick={() => void send()} disabled={loading} className="w-full">{loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}Send to {numbers.length || "recipients"}</Button></CardContent></Card>;
}
