// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Route deployed browser requests through the app origin so custom domains avoid Supabase CORS failures.
const isLocalHost = /^(localhost|127\.0\.0\.1)$/.test(window.location.hostname);
const SUPABASE_URL = isLocalHost
  ? "https://uloaiqmknsrknqikbmtb.supabase.co"
  : `${window.location.origin}/supabase`;
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsb2FpcW1rbnNya25xaWtibXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3MDMxNTksImV4cCI6MjA4OTI3OTE1OX0.vegCKSDJlFT8DKoU99pMCskhrS1XUCLKg2PXXInPub0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});
